language: python
env:
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=flake8
install:
  - pip install tox
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - tox -e $TOX_ENV
  - py.test --cov=afinn tests
after_success:
  coveralls