language: python
env:
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=flake8
install:
  - pip install tox
  - pip install coverage
  - pip install coveralls
script:
  - tox -e $TOX_ENV
  - coverage run --source=afinn setup.py test
after_success:
  coveralls